require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: ~3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/InitialIndentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/YAMLLoad:
  Enabled: false
