inherit_from: .rubocop_todo.yml

# Rails-generated boilerplate this app doesn't hand-author.
AllCops:
  Exclude:
    - 'db/*schema.rb'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Procfile'
    - 'Procfile.dev'
