AllCops:
  TargetRubyVersion: ~3.2
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/importmap.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
